## Write a Numpy program to compute the multiplication of two given matrixes

In [3]:
import numpy as np
mat1 = np.arange(1,13).reshape(4,3)
mat2 = np.arange(1,10).reshape(3,3)
result=np.dot(mat1,mat2)

In [4]:
print(result)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]
 [138 171 204]]


## Write a NumPy program to compute the determinant of a given square array

In [5]:
a = np.linalg.det(mat2)
print("Determinant of 3-D array:")
print(a)

Determinant of 3-D array:
0.0


## Write a NumPy program to compute the cross product of two given vectors

In [6]:
vector1 = [[1, 0], [0, 1]]
vector2 = [[1, 2], [3, 4]]
result1 = np.cross(vector1, vector2)
print("cross product of the said two vectors(p, q):")
print(result1)


cross product of the said two vectors(p, q):
[ 2 -3]


## Write a NumPy program to compute the condition number of a given matrix
the condition number of a function measures how much the output value of the function can change for a small change in the input argument. This is used to measure how sensitive a function is to changes or errors in the input, and how much error in the output results from an error in the input.

*hint: look for something similar in the `linalg` module*

In [7]:
matrix = np.arange(1,13).reshape(4,3) 
result =  np.linalg.cond(matrix) 
print("Condition number of the matrix:")
print(result)

Condition number of the matrix:
1.1014420422566856e+16


## Write a NumPy program to compute the inverse of a given matrix

In [16]:
matrix = np.arange(5,9).reshape(2,2) 
result =  np.linalg.inv(matrix)
print(result)

[[-4.   3. ]
 [ 3.5 -2.5]]
